ccflags-y += -I$(src)/../include

# Core module
fbtft-y	+= fbtft-core.o fbtft-bus.o fbtft-io.o
obj-m	+= fbtft.o

# Drivers
obj-m	+= fb_bd663474.o
obj-m	+= fb_hx8347d.o
obj-m	+= fb_ili9163.o
obj-m	+= fb_pcd8544.o
obj-m	+= fb_ra8875.o
obj-m	+= fb_s6d1121.o
obj-m	+= fb_ssd1289.o
obj-m	+= fb_ssd1305.o
obj-m	+= fb_ssd1306.o
obj-m	+= fb_ssd1325.o
obj-m	+= fb_ssd1331.o
obj-m	+= fb_ssd1351.o
obj-m	+= fb_tls8204.o
obj-m	+= fb_uc1701.o
obj-m	+= fb_upd161704.o
obj-m	+= fb_watterott.o
